### PR TITLE
adding a lot of install targets and fixing dependencies

### PR DESCRIPTION
**Pull request by marc-hanheide**
In an effort to make this pipelines release-able and install-able as part of the [ILIAD project](http://iliad-project.eu/), I had to fix a number of dependencies and also added numerous install targets that were missing. I don't think this is complete yet. So, don't merge just yet... Just making people aware that I'm doing this. There may be other commits to this PR as I complete this endeavour.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
apologies that is just getting bigger and bigger, but many packages lacked proper dependency definitions and install targets. I'm still convinced many things are not installed correctly, but at least most of the packages build now in a standard ROS build farm for kinectic. Current status here: https://lcas.lincoln.ac.uk/buildfarm/view/Kbin_uX64/

**Comment by tlind** [comment]
Hi Marc, sure, no problem! Thanks for your really great effort first of all! Maybe I can try to fix the remaining missing install targets next week. We never used them during the SPENCER project, so it is clear that a lot of them are missing. I see e.g. the `srl_nearest_neighbor_tracker` still missing its targets. I guess it would suffice to fix and test them locally in the catkin install space?

One thing that confuses me, though, are the changes to README.md by strands-jenkins (and the addition of tracks.yaml). Are they supposed to end up in the master branch, or should we create a separate branch or repository for those?

**Comment by marc-hanheide** [comment]
OK, the changes in the README.md and the `tracks.yaml` are created, because I - against all recommendations - also used the same repo as release repo. I can change that again and create a separate release repo if you prefer. Otherwise, at least it all builds now and packages have all been successfully created. Now, somebody would have to try them and see if the actually work as intended when installed as binaries.

**Comment by tlind** [comment]
I agree on the metapackage, had the same idea last week :-). I'll take care of that, as well as fixing the remaining binary issues.

Regarding the release repo, I don't really care about the `tracks.yaml`, but the main README file gets filled up with "garbage" and it is the only form of documentation that we currently have.

**Comment by marc-hanheide** [comment]
I have now removed all the bits that came from using this as a release repo, too. Stupid idea in the first place. This should now be clean, and I'll trigger a new full release build of it in a minute.

**Comment by tlind** [comment]
Cool, thanks! Did the release process succeed? Shall I merge this PR now?

**Comment by marc-hanheide** [comment]
The release build was successful but I don't know for such if it really contains all the required files to run it as I don't have complete knowledge to check if all was installed using the install targets. Maybe you could try running the released packages? Otherwise I think the pr can be merged, but we may have to add more install targets.

**Comment by tlind** [comment]
I already saw last time that some files/targets are still missing, but I can fix them in a second step and commit the necessary changes directly to this repository.

**Comment by marc-hanheide** [comment]
👍

**Comment by tlind** [comment]
@marc-hanheide I think I have fixed most of the missing install targets. I've also added a new metapackage called `spencer_people_tracking_full`. Can you trigger another release build?

**Pull request merged**
